### ISSUE TITLE
ArrayInitializer Expression failed to Reduce with default constructor of value type

### ISSUE THREAD

**Issue by acaly** [sagifogel/NJection.LambdaConverter#3]
Hi!
First I want to say thank you for such a helpful library. But I came across with an issue.

With an short example like
```C#
public struct TestStruct { public float X; }
public static TestStruct TestFunction()
{
    TestStruct ret = new TestStruct();
    ret.X = 1;
    return ret;
}
```
The Expression object is constructed like this
```C#
 var lambda = Lambda.TransformMethodTo<Func<TestStruct>>()
                    .From(() => TestFunction)
                    .ToLambda();
```
And when I try to reduce every node in the expression tree, like this (though a little bit ugly, this shows exactly what I have done on it)
```C#
var x1 = lambda.Body.ReduceExtensions();
var xx1 = (InvocationExpression)x1;
var x2 = xx1.Expression;
var xx2 = (Expression<Func<TestStruct>>)x2;
var x3 = xx2.Body.ReduceExtensions();
var xx3 = (BlockExpression)x3;
var x4 = xx3.Expressions[0].ReduceExtensions();
var xxx4 = (GotoExpression)x4;
var xx5 = xxx4.Value.ReduceExtensions();
```
An exception occurs. I tried replacing the ```ReduceExtensions``` method with two ```Reduce``` method calls, and it seems that this is caused by a null pointer in ```ArrayInitializer``` expression. I have also noted that if I remove the ```ret.X = 1;```, the final reduce method does return a DefaultExpression.

**Comment by sagifogel** [comment]
Fixed.
Thanks for the feedback
